scanner:
    linter: flake8

flake8:
    max-line-length: 100
    ignore:
        - E203
        - E501
        - W504

message:
    opened:
        header: "Hello @{name}! Thanks for opening this PR. "
    updated:
        header: "Hello @{name}! Thanks for updating this PR. "
    no_errors: "There are currently no PEP 8 issues detected in this Pull Request. Cheers! :beers: "
